Add convert_prefecture() function
uribo/zipangu pull request #48
Opened 2022-04-21 14:52 UTC by Doubt-0KB

#47 で提案させていただいた都道府県名を変換する関数を追加しました。

- 漢字⇔ローマ字の相互変換
```{r}
convert_prefecture(c("tokyo", "osaka", "ALL"), to="kanji")
#> [1] "東京都" "大阪府" "全国"

convert_prefecture(c("東京", "大阪府", "北海道", "全国"), to="roman")
#> [1] "Tokyo-to" "Osaka-fu" "Hokkaido" "All"
```

- ひらがな・カタカナ→漢字の変換
```{r}
convert_prefecture_from_hirakana(c("トウキョウト", "おおさか"))
#> [1] "東京都" "大阪府"

convert_prefecture_from_hirakana(c("キョウト", "おおさか"))
#> [1] "京都府" "大阪府"
```

2022-04-26 06:30 UTC, uribo commented
@Doubt-0KB 確認が遅くなりまして申し訳ありません。
現在いただいている実装では`devtools::check()`に引っ掛かっていますので、テストを通るように修正いただけますでしょうか。

問題となっている箇所はコード中のマルチバイト文字です。これらの文字列は `\uxxxx` の形式でエスケープしておく必要があります。

2022-05-01 12:11 UTC, Doubt-0KB commented
マルチバイト文字のエスケープ対応について実施しました。

また、手元で確認していたところ都道府県名の一部だけでも変換ができてしまうバグがあったため、完全一致した場合に変換するように変更しました。

```{r}
#修正前
convert_prefecture("O", to="kanji")
#> [1] "大阪府"

#修正後
convert_prefecture("O", to="kanji")
#> Error in convert_prefecture_to_kanji(x) : 存在しない地域が含まれています
```

それに伴い、関数が冗長にならないよう各種の都道府県名を変数化しました。現状では関数の冒頭に並べていますが、必要であれば別にファイルで追加する形にします。

2022-05-02 02:35 UTC, uribo commented on R/convert_prefecture.R
> +prefecture_kanji_long <- c("\u5317\u6d77\u9053","\u9752\u68ee\u770c","\u5ca9\u624b\u770c",
`prefecture_kanji_long`, `prefecture_kanji_short`は`convert_prefecture_from_hirakana.R`でも定義されているので冗長かと思います。

2022-05-02 02:37 UTC, uribo requested changes
testコードの作成、NEWS.mdへの関数追加の文章を追加いただけますか？

2022-05-02 02:39 UTC, uribo commented
コメントですが、`prefecture_kanji_long`,`prefecture_kanji_short`等、都道府県名のベクトルをたくさん作るのもややこしいので、これらのベクトルを一つのリストにまとめるのはどうでしょうか

2022-05-04 08:53 UTC, Doubt-0KB commented
コメントありがとうございます。
都道府県名の各ベクトルについてはリスト化で対応しました。
また、NEWS.mdへの文章追加とtestコードの作成についても実施しました。

2022-05-04 09:38 UTC, merged

2022-05-04 09:39 UTC, uribo commented
@Doubt-0KB 対応いただき、ありがとうございました。マージさせていただきました。#47 close となります。